### ISSUE TITLE
github package in package.json

### ISSUE THREAD

**Issue by jharris4** [lokesh/color-thief#172]
Hi, I just noticed that the [quantize](https://github.com/lokesh/quantize) package is being pulled from your github fork in package.json:

```
"quantize": "github:lokesh/quantize"
```

Is there any reason for not publishing this fork to npm so that it can be accessed directly from the npm registry?

**Comment by asharimh97** [comment]
I am asking the same reason right now, my docker won't build because of that.

It returned `npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/lokesh/quantize.git`

**Comment by himadrinath** [comment]
@lokesh :confused:

**Comment by lokesh** [comment]
I'll look into publishing to the global npm registry this weekend. I didn't expect the access issues. Thanks for calling out.

**Comment by afonsomatos** [comment]
Is this done?

**Comment by afonsomatos** [comment]
Please make this happen. We are having access issues.

**Comment by afonsomatos** [comment]
@lokesh

**Comment by AlfredJKwack** [comment]
@afonsomatos why don't you submit a pull request? 
That might be a bit more constructive than spamming don't you agree?

**Comment by afonsomatos** [comment]
The owner has to publish it to npm, not me. @AlfredJKwack

**Comment by cxxxxxn** [comment]
We also have access issues. Looking forward to this issue being resolved soon!

**Comment by laverdet** [comment]
I've published `@laverdet/lokesh-colorthief@2.3.2` and `@laverdet/lokesh-quantize@1.2.0` to npm which breaks the github dependency. Feel free to update your packages to that location. The code is directly from github, and republished to npm.

**Comment by hituraj** [comment]
> I'll look into publishing to the global npm registry this weekend. I didn't expect the access issues. Thanks for calling out.

Still not working:

19:22:28 npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/lokesh/quantize.git
19:22:28 npm ERR! ssh: connect to host github.com port 22: No route to host
19:22:28 npm ERR! fatal: Could not read from remote repository.

**Comment by lokesh** [comment]
Finally... done. The package on npmjs.com:
https://www.npmjs.com/package/@lokesh.dhakar/quantize

The latest release of color-thief v2.4.0 updates the quantize dep reference in package.json:
https://github.com/lokesh/color-thief/releases/tag/v2.4.0
